version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger.yaml
    ports:
      - "8080:8080"