openapi: 3.0.2

info:
  version: 0.0.0
  title: DAIKIN API

paths:
  /common/basic_info:
    $ref: ./swagger/common/basic_info.yaml
  /common/get_datetime:
    $ref: ./swagger/common/get_datetime.yaml
  /common/get_notify:
    $ref: ./swagger/common/get_notify.yaml
  /common/notify_date_time:
    $ref: ./swagger/common/notify_date_time.yaml
  /cleaner/get_model_info:
    get:
      tags:
        - cleaner
      description: |
        モデルの情報を取得
      responses:
        '200':
          description: |
            モデルの情報
  /cleaner/get_unit_info:
    get:
      tags:
        - cleaner
      description: |
        ユニットの情報を取得
      responses:
        '200':
          description: |
            ユニットの情報を取得

components:
  schemas:
    BasicInfo:
      $ref: "./swagger/schema/basic_info.yaml"
    GetDatetime:
      $ref: "./swagger/schema/get_datetime.yaml"
    GetNotify:
      $ref: "./swagger/schema/get_notify.yaml"
    Success:
      $ref: "./swagger/schema/success.yaml"
