swagger: "2.0"
info:
  version: "0.0.0"
  title: DAIKEN API

paths:
  /common/basic_info:
    $ref: "./swagger/common/basic_info.yaml"
  /common/get_datetime:
    $ref: "./swagger/common/get_datetime.yaml"
  /common/get_notify:
    $ref: "./swagger/common/get_notify.yaml"

definitions:
  basic_info:
    $ref: "./swagger/definition/basic_info.yaml"
  get_datetime:
    $ref: "./swagger/definition/get_datetime.yaml"
  get_notify:
    $ref: "./swagger/definition/get_notify.yaml"
