openapi: 3.0.2

info:
  version: 0.0.0
  title: DAIKIN API
  description: |
    json 形式で記述しているが、
    実際は key と value を = で繋いだコンマ区切りの形式でレスポンスが返ってくる。

paths:
  /common/basic_info:
    $ref: ./paths/common/basic_info.yaml
  /common/get_datetime:
    $ref: ./paths/common/get_datetime.yaml
  /common/get_notify:
    $ref: ./paths/common/get_notify.yaml
  /common/notify_date_time:
    $ref: ./paths/common/notify_date_time.yaml
  /common/get_wifi_setting:
    $ref: ./paths/common/get_wifi_setting.yaml
  /common/look_adapter:
    $ref: ./paths/common/look_adapter.yaml
  /common/stop_look_adapter:
    $ref: ./paths/common/stop_look_adapter.yaml

  /cleaner/get_model_info:
    $ref: ./paths/cleaner/get_model_info.yaml
  /cleaner/get_unit_info:
    $ref: ./paths/cleaner/get_unit_info.yaml
  /cleaner/get_control_info:
    $ref: ./paths/cleaner/get_control_info.yaml
  /cleaner/set_control_info:
    $ref: ./paths/cleaner/set_control_info.yaml
  /cleaner/get_sensor_info:
    $ref: ./paths/cleaner/get_sensor_info.yaml
  /cleaner/get_unit_status:
    $ref: ./paths/cleaner/get_unit_status.yaml
  /cleaner/get_device_setting:
    $ref: ./paths/cleaner/get_device_setting.yaml
  /cleaner/get_day_snsr_count:
    $ref: ./paths/cleaner/get_day_snsr_count.yaml
  /cleaner/get_week_snsr_count:
    $ref: ./paths/cleaner/get_week_snsr_count.yaml

components:
  schemas:
    BasicInfo:
      $ref: "./schema/basic_info.yaml"
    GetDatetime:
      $ref: "./schema/get_datetime.yaml"
    GetNotify:
      $ref: "./schema/get_notify.yaml"
    GetWifiSetting:
      $ref: "./schema/get_wifi_setting.yaml"
    GetModelInfo:
      $ref: "./schema/get_model_info.yaml"
    GetUnitInfo:
      $ref: "./schema/get_unit_info.yaml"
    GetControlInfo:
      $ref: "./schema/get_control_info.yaml"
    GetSensorInfo:
      $ref: "./schema/get_sensor_info.yaml"
    GetUnitStatus:
      $ref: "./schema/get_unit_status.yaml"
    GetDeviceSetting:
      $ref: "./schema/get_device_setting.yaml"
    GetDaySnsrCount:
      $ref: "./schema/get_day_snsr_count.yaml"
    GetWeekSnsrCount:
      $ref: "./schema/get_week_snsr_count.yaml"
    Success:
      $ref: "./schema/success.yaml"

tags:
  - name: common
    description: 機器に関する情報の取得、登録の API 群
  - name: cleaner
    description: 空気清浄機に関する情報の取得、登録の API 群
